[build]
target = "riscv32imc-esp-espidf"

[target.riscv32imc-esp-espidf]
linker = "ldproxy"
# runner = "espflash --monitor" # Uncomment to flash and monitor automatically

[unstable]
build-std = ["std", "panic_abort"]

[env]
# ESP-IDF configuration
ESP_IDF_VERSION = "v5.1.2"
ESP_IDF_SDKCONFIG_DEFAULTS = "sdkconfig.defaults"

# Logging configuration
RUST_LOG = "info"